export const data = JSON.parse("{\"key\":\"v-9a202798\",\"path\":\"/front-end/Typescript/ts01-%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html\",\"title\":\"ts01-数据类型\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"ts01-数据类型\",\"index\":true,\"icon\":\"laptop-code\",\"category\":[\"Typescript\"],\"description\":\"基础数据类型 字符串 let str: string = \\\"字符串\\\"; console.log(str, typeof str); //输出：字符串，string\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"http://www.mashimaro.top/front-end/Typescript/ts01-%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"ts01-数据类型\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"基础数据类型 字符串 let str: string = \\\"字符串\\\"; console.log(str, typeof str); //输出：字符串，string\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"LJK\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"ts01-数据类型\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"LJK\\\",\\\"url\\\":\\\"http://www.mashimaro.top/\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"基础数据类型\",\"slug\":\"基础数据类型\",\"link\":\"#基础数据类型\",\"children\":[]},{\"level\":2,\"title\":\"高级数据类型\",\"slug\":\"高级数据类型\",\"link\":\"#高级数据类型\",\"children\":[]}],\"readingTime\":{\"minutes\":0.35,\"words\":105},\"filePathRelative\":\"front-end/Typescript/ts01-数据类型.md\",\"excerpt\":\"<h2> 基础数据类型</h2>\\n<h4> 字符串</h4>\\n<div class=\\\"language-typescript line-numbers-mode\\\" data-ext=\\\"ts\\\"><pre class=\\\"language-typescript\\\"><code><span class=\\\"token keyword\\\">let</span> str<span class=\\\"token operator\\\">:</span> <span class=\\\"token builtin\\\">string</span> <span class=\\\"token operator\\\">=</span> <span class=\\\"token string\\\">\\\"字符串\\\"</span><span class=\\\"token punctuation\\\">;</span>\\n<span class=\\\"token builtin\\\">console</span><span class=\\\"token punctuation\\\">.</span><span class=\\\"token function\\\">log</span><span class=\\\"token punctuation\\\">(</span>str<span class=\\\"token punctuation\\\">,</span> <span class=\\\"token keyword\\\">typeof</span> str<span class=\\\"token punctuation\\\">)</span><span class=\\\"token punctuation\\\">;</span>\\n<span class=\\\"token comment\\\">//输出：字符串，string</span>\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
